# fly.toml app configuration file generated for backend-tfg on 2026-05-24T01:27:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-tfg'
primary_region = 'ams'

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  memory_mb = 512
  size = 'shared-cpu-1x'
