spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=monumentos_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/prueba_monumentos?user=postgres
spring.datasource.username=postgres
spring.datasource.password=asdfASDF_4
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# docker run --name postgresHistoria -e POSTGRES_PASSWORD=asdfASDF_4 -p 5432:5432 -v postgres_data_nuevo:/var/lib/postgresql -d postgres:latest