spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=monumentos_backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.axhthfoqdxickibsblrq&password=G0XmG4hnq7ujppzG
spring.datasource.username=postgres.axhthfoqdxickibsblrq
spring.datasource.password=G0XmG4hnq7ujppzG
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl